[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
tokenized_vaults_program = "63JRAaqV5J7RZ2muRqfhBoNyadtLSChKenKZqjvt4gyL"

[programs.devnet]
tokenized_vaults_program = "63JRAaqV5J7RZ2muRqfhBoNyadtLSChKenKZqjvt4gyL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
